Config = {}
Config.ZDistance = 30.0
Config.Distance = 20.0

Config.Templates = {
    -- ["looc"] = '<div class="custom_message" style="background-color: rgba(128, 128, 128, 0.5);"><div style="display: block"><i class="fas fa-comment"></i> {1} <span style = "font-weight: 600">[{0}]</span>: {2}</div></div>',
    ["looc"] = '<div class="new_chat_template" style="background-color: rgba(0, 0, 0, 0.6); border-radius: 10px;"><div class="image" style="background-color: rgba(94, 94, 94, 0.5);"><i class="fas fa-comment"></i></div><div class="args"><div class="title">[{0}] {1}</div><div class="content">{2}</div></div></div>',
    -- ['twt'] = '<div class="custom_message" style="background-color: rgba(0, 200, 255, 0.5);"><div style="display: block"><i class="fab fa-twitter"></i> <span style = "font-weight: 600">&nbsp;{1}</span>: {2}</div></div>',
    -- ['twt_id'] = '<div class="custom_message" style="background-color: rgba(0, 200, 255, 0.5);"><div style="display: block"><i class="fab fa-twitter"></i> <span style = "font-weight: 600">&nbsp;[{0}] {1}</span>: {2}</div></div>',
    ["twt"] = '<div class="new_chat_template" style="background-color: rgba(0, 0, 0, 0.6); border-radius: 10px;"><div class="image" style="background-color: rgba(42, 143, 214, 0.5);"><i class="fab fa-twitter"></i></div><div class="args"><div class="title">{1}</div><div class="content">{2}</div></div></div>',
    ["twt_id"] = '<div class="new_chat_template" style="background-color: rgba(0, 0, 0, 0.6); border-radius: 10px;"><div class="image" style="background-color: rgba(42, 143, 214, 0.5);"><i class="fab fa-twitter"></i></div><div class="args"><div class="title">[{0}] {1}</div><div class="content">{2}</div></div></div>',
    ["dw"] = '<div class="new_chat_template" style="background-color: rgba(0, 0, 0, 0.6); border-radius: 10px;"><div class="image" style="background-color: rgba(46, 0, 82, 0.5);"><i class="fa fa-desktop"></i></div><div class="args"><div class="title">[{0}] Anonim</div><div class="content">{2}</div></div></div>',
    ["dw_id"] = '<div class="new_chat_template" style="background-color: rgba(0, 0, 0, 0.6); border-radius: 10px;"><div class="image" style="background-color: rgba(46, 0, 82, 0.5);"><i class="fa fa-desktop"></i></div><div class="args"><div class="title">[{0}] Anonim</div><div class="content">{2}</div></div></div>',
    ["dw2"] = '<div class="new_chat_template" style="background-color: rgba(0, 0, 0, 0.6); border-radius: 10px;"><div class="image" style="background-color: rgba(46, 0, 82, 0.5);"><i class="fa fa-desktop"></i></div><div class="args"><div class="title">{1}</div><div class="content">{2}</div></div></div>',
    ["dw2_id"] = '<div class="new_chat_template" style="background-color: rgba(0, 0, 0, 0.6); border-radius: 10px;"><div class="image" style="background-color: rgba(46, 0, 82, 0.5);"><i class="fa fa-desktop"></i></div><div class="args"><div class="title">[{0}] {1}</div><div class="content">{2}</div></div></div>',
    -- ['me'] = '<div class="custom_message" style="background-color: rgba(57, 247, 212, 0.5);"><div style="display: block"><i class="fas fa-user-circle"></i>&nbsp;<span style = "font-weight: 600">&nbsp;[{0}]</span>: {2}</div></div>',
    ["me"] = '<div class="new_chat_template" style="background-color: rgba(0, 0, 0, 0.6); border-radius: 10px;"><div class="image" style="background-color: rgba(57, 247, 212, 0.5);"><i class="fas fa-user-circle"></i></div><div class="args"><div class="title">[{0}] {1}</div><div class="content">{2}</div></div></div>',
    -- ['do'] = '<div class="custom_message" style="background-color: rgba(163, 0, 133, 0.5);"><div style="display: block"><i class="fas fa-user-circle"></i>&nbsp;<span style = "font-weight: 600">&nbsp;[{0}]</span>: {2}</div></div>',
    ["do"] = '<div class="new_chat_template" style="background-color: rgba(0, 0, 0, 0.6); border-radius: 10px;"><div class="image" style="background-color: rgba(163, 0, 133, 0.5);"><i class="fas fa-user-circle"></i></div><div class="args"><div class="title">[{0}] {1}</div><div class="content">{2}</div></div></div>',
    -- ['try'] = '<div class="custom_message" style="background-color: rgba(%s, 0.5);"><div style="display: block"><i class="fas fa-user-circle"></i>&nbsp;<span style = "font-weight: 600">&nbsp;[{0}]</span>: {2}</div></div>',
    ["try"] = '<div class="new_chat_template" style="background-color: rgba(0, 0, 0, 0.6); border-radius: 10px;"><div class="image" style="background-color: rgba(%s, 0.5);"><i class="fas fa-user-circle"></i></div><div class="args"><div class="title">[{0}] {1}</div><div class="content">{2}</div></div></div>',
    -- ['ambulance'] = '<div class="custom_message" style="background-color: rgba(255, 0, 0, 0.5);"><div style="display: block"><i class="fa fa-desktop"></i> <span style = "font-weight: 600">&nbsp;{1}:</span> {2}</div></div>',
    ["ambulance"] = '<div class="new_chat_template" style="background-color: rgba(0, 0, 0, 0.6); border-radius: 10px;"><div class="image" style="background-color: rgba(255, 0, 0, 0.5);"><i class="fa fa-desktop"></i></div><div class="args"><div class="title">[{0}] {1}</div><div class="content">{2}</div></div></div>',
    -- ['police'] = '<div class="custom_message" style="background-color: rgba(0, 0, 255, 0.5);"><div style="display: block"><i class="fa fa-desktop"></i> <span style = "font-weight: 600">&nbsp;{1}:</span> {2}</div></div>',
    ["police"] = '<div class="new_chat_template" style="background-color: rgba(0, 0, 0, 0.6); border-radius: 10px;"><div class="image" style="background-color: rgba(0, 0, 255, 0.5);"><i class="fa fa-desktop"></i></div><div class="args"><div class="title">[{0}] {1}</div><div class="content">{2}</div></div></div>',
    -- ['mechanik'] = '<div class="custom_message" style="background-color: rgba(0, 0, 255, 0.5);"><div style="display: block"><i class="fa fa-desktop"></i> <span style = "font-weight: 600">&nbsp;{1}:</span> {2}</div></div>',
    ["mechanik"] = '<div class="new_chat_template" style="background-color: rgba(0, 0, 0, 0.6); border-radius: 10px;"><div class="image" style="background-color: rgba(187, 255, 0, 0.5);"><i class="fa fa-desktop"></i></div><div class="args"><div class="title">[{0}] {1}</div><div class="content">{2}</div></div></div>',
     ["news"] = '<div class="new_chat_template" style="background-color: rgba(0, 0, 0, 0.6); border-radius: 10px;"><div class="image" style="background-color: rgba(255, 187, 41, 0.5);"><i class="fa fa-desktop"></i></div><div class="args"><div class="title">{1}</div><div class="content">{2}</div></div></div>',
    -- ['report'] = '<div class="custom_message" style="background-color: rgba(255, 106, 0, 0.5);"><div style="display: block"><i class="fas fa-flag"></i> {1} <span style = "font-weight: 600">[{0}]</span>: {2}</div></div>',
    ["report"] = '<div class="new_chat_template" style="background-color: rgba(0, 0, 0, 0.6); border-radius: 10px;"><div class="image" style="background-color: rgba(255, 106, 0, 0.5);"><i class="fas fa-flag"></i></div><div class="args"><div class="title">{1} [{0}]</div><div class="content">{2}</div></div></div>',
    -- ['error'] = '<div class="custom_message" style="background-color: rgba(255, 102, 0, 0.5);"><div style="display: block"> <i class="fas fa-exclamation-circle"></i> &nbsp;<span>{0}</span></div></div>',
    ["error"] = '<div class="new_chat_template" style="background-color: rgba(0, 0, 0, 0.6); border-radius: 10px;"><div class="image" style="background-color: rgba(255, 0, 0, 0.5);"><i class="fas fa-exclamation-circle"></i></div><div class="args"><div class="title">SYSTEM</div><div class="content">{0}</div></div></div>',
    -- ['adminchat'] = '<div class="custom_message" style="background-color: rgba(100, 0, 155, 0.5);"><div style="display: block"><i class="fas fa-shield-alt"></i>&nbsp;<span style = "font-weight: 600">ADMIN CHAT:</span> {1}<span style = "font-weight: 600"> [{0}]</span>: {2} </div></div>',
    ["adminchat"] = '<div class="new_chat_template" style="background-color: rgba(0, 0, 0, 0.6); border-radius: 10px;"><div class="image" style="background-color: rgba(100, 0, 155, 0.5);"><i class="fas fa-shield-alt"></i></div><div class="args"><div class="title">ADMIN CHAT: {1} [{0}]</div><div class="content">{2}</div></div></div>',
    -- ['ogloszenie'] = '<div class="custom_message" style="background-color: rgba(205, 0, 0, 0.5);"><div style="display: block"><i class="fas fa-shield-alt"></i>&nbsp;{1}<span style = "font-weight: 600"></span>: {2} </div></div>',
    ["ogloszenie"] = '<div class="new_chat_template" style="background-color: rgba(0, 0, 0, 0.6); border-radius: 10px;"><div class="image" style="background-color: rgba(205, 0, 0, 0.5);"><i class="fas fa-shield-alt"></i></div><div class="args"><div class="title">OGŁOSZENIE OD: {1}</div><div class="content">{2}</div></div></div>',
    -- ['privatemessageget'] = '<div class="custom_message" style="background-color: rgba(100, 0, 155, 0.5);"><div style="display: block"><i class="fas fa-user"></i>&nbsp;<span style = "font-weight: 600">WIADOMOŚĆ PRYWATNA OD: {1}:</span> {2} </div></div>',
    ["privatemessageget"] = '<div class="new_chat_template" style="background-color: rgba(0, 0, 0, 0.6); border-radius: 10px;"><div class="image" style="background-color: rgba(100, 0, 155, 0.5);"><i class="fas fa-user"></i></div><div class="args"><div class="title">WIADOMOŚĆ PRYWATNA OD: {1}</div><div class="content">{2}</div></div></div>',
    -- ['privatemessagesend'] = '<div class="custom_message" style="background-color: rgba(100, 0, 155, 0.5);"><div style="display: block"><i class="fas fa-user"></i>&nbsp;<span style = "font-weight: 600">WIADOMOŚĆ PRYWATNA DO: {1}:</span> {2} </div></div>',
    ["privatemessagesend"] = '<div class="new_chat_template" style="background-color: rgba(0, 0, 0, 0.6); border-radius: 10px;"><div class="image" style="background-color: rgba(100, 0, 155, 0.5);"><i class="fas fa-user"></i></div><div class="args"><div class="title">WIADOMOŚĆ PRYWATNA DO: {1}</div><div class="content">{2}</div></div></div>',
    -- ['sent'] = '<div class="custom_message" style="background-color: rgba(42, 219, 7, 0.5);"><div style="display: block"> <i class="fas fa-check"></i>&nbsp; <span>Wiadomość została wysłana!</span></div></div>',
    ["sent"] = '<div class="new_chat_template" style="background-color: rgba(0, 0, 0, 0.6); border-radius: 10px;"><div class="image" style="background-color: rgba(42, 219, 7, 0.5);"><i class="fas fa-user"></i></div><div class="args"><div class="title">SYSTEM</div><div class="content">Wiadomość została wysłana!</div></div></div>',
    ["mandat"] = '<div class="new_chat_template" style="background-color: rgba(0, 0, 0, 0.6); border-radius: 10px;"><div class="image" style="background-color: rgba(148, 251, 255, 0.5);"><i class="fas fa-money-bill"></i></div><div class="args"><div class="title">MANDAT</div><div class="content">{0} otrzymał mandat w wysokość {1} za {2} | Funkcjonariusz {3}</div></div></div>',
    ["wiezienie"] = '<div class="new_chat_template" style="background-color: rgba(0, 0, 0, 0.6); border-radius: 10px;"><div class="image" style="background-color: rgba(148, 251, 255, 0.5);"><i class="fas fa-money-bill"></i></div><div class="args"><div class="title">WIEZENIE</div><div class="content">{0} otrzymał wyrok na {1} miesięcy za {2} | Funkcjonariusz {3}</div></div></div>',
    ["faktura"] = '<div class="new_chat_template" style="background-color: rgba(0, 0, 0, 0.6); border-radius: 10px;"><div class="image" style="background-color: rgba(148, 251, 255, 0.5);"><i class="fas fa-money-bill"></i></div><div class="args"><div class="title">FAKTURA</div><div class="content">{0} otrzymał fakturę w wysokość {1} za {2}</div></div></div>',
    ["smieciarka"] = '<div class="new_chat_template" style="background-color: rgba(0, 0, 0, 0.6); border-radius: 10px;"><div class="image" style="background-color: rgba(255, 107, 107, 0.5);"><i class="fas fa-trash"></i></div><div class="args"><div class="title">ŚMIECIARKA</div><div class="content">{0}</div></div></div>',
    ["centrala"] = '<div class="new_chat_template" style="background-color: rgba(0, 0, 0, 0.6); border-radius: 10px;"><div class="image" style="background-color: rgba(10, 10, 10, 0.5);"><i class="fas fa-laptop"></i></div><div class="args"><div class="title">CENTRALA</div><div class="content">{0}</div></div></div>',
}

Config.Colours = {
    ['me'] = {57, 247, 212},
    ['do'] = {163, 0, 133},
    ['try'] = {39, 45, 168},
    ['dice'] = {39, 142, 168},
    ['roll'] = {137, 73, 145},
    ['drop'] = {0, 95, 181}
}

Config.TryMessageColours = {
    [0] = "230, 0, 0",
    [1] = "0, 217, 0",
    [2] = "66, 179, 245"
}